[env]
PKG_CONFIG_ALLOW_CROSS = "1"
PKG_CONFIG_PATH = { value = ".cargo/pkgconfig", relative = true }

[target.wasm32-unknown-emscripten]
rustflags = [
  "-C",
  "link-arg=--no-entry",
  "-C",
  "link-arg=-sSTANDALONE_WASM=1",
  "-C",
  "link-arg=-sALLOW_MEMORY_GROWTH=1",
  "-C",
  "link-arg=-sINITIAL_MEMORY=268435456",
]
